filebeat.config.modules:

  path: ${path.config}/modules.d/*.yml

  reload.enabled: false

setup.dashboards.enabled: true

setup.kibana:
  host: "192.168.30.4:5601"

output.logstash:
  hosts: ['192.168.30.4:5044']

# output.elasticsearch:
#   hosts: ["192.168.30.4:9200"]